# Download vcfs from https://basespace.illumina.com/s/otSPW8hnhaZR
# to data/resources/

fasta:
  hg19:
    url: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz
    file: data/resources/GRCh37.primary_assembly.genome.fa

precomputed:
  snv: data/resources/spliceai_scores.masked.snv.{genome}.vcf.gz
  indel: data/resources/spliceai_scores.masked.indel.{genome}.vcf.gz

# genome version hg19 or hg38 
genome: hg19

# add your vcf file to here
vcf: data/resources/test.vcf.gz

# path of rocksdb for look up for precomputed scores

rocksdb: data/results/spliceAI_{genome}.db/

rockdb_backup: data/results/backups/spliceAI_rocksdb_{genome}/

# predictions
result: data/results/spliceAI_{genome}.csv

# too large batch_size may cause memory error
batch_size: 10000
