# Download vcfs from https://basespace.illumina.com/s/otSPW8hnhaZR
# to data/resources/

precomputed:
  grch37:
    snv: data/resources/spliceai_scores.masked.indel.hg19.vcf.gz
    indel: data/resources/spliceai_scores.masked.indel.hg19.vcf.gz
  grch38:
    snv: data/resources/spliceai_scores.masked.snv.hg38.vcf.gz
    indel: data/resources/spliceai_scores.masked.indel.hg38.vcf.gz

rocksdb: data/results/spliceAI_{genome}.db/
rockdb_backup: data/results/backups/spliceAI_rocksdb_{version}
  
# too large batch_size may cause memory error
batch_size: 10000
