configfile: "config.yaml"


rule all:
    input:
        expand(config['rockdb_backup'], genome=config['genome']), 
        expand(config['result'], genome=config['genome'])

rule download_human_fasta:
    params:
        config['fasta'][genome]['url']
    output:
        config['fasta'][genome]['file']
    shell:
        "wget -O - {params} | gunzip -c > {output}"

rule create_spliceAI_rocksDB:
    input:
        snv = config['precomputed']['snv'],
        indel = config['precomputed']['indel']
    params:
        batch_size = config['batch_size']
    output:
        db = directory(config['rocksdb'])
    script:
        "./scripts/create_rocksdb.py"


rule backup_rocksdb:
    input:
        db = config['rocksdb']
    output:
        backup = directory(config['rockdb_backup']),
        backup_gzip = config['rockdb_backup'] + '.tar.gz'
    script:
        "./scripts/backup_rocksdb.py"

def fasta(wildcards):
    genome = wildcards['genome']
    return config['fasta'][genome]['file']

rule predict_spliceAI:
    threads: 1
    resources:
        ntasks = 1,
        mem_mb = 8000,
        gpu = 1,
    input:
        fasta = fasta,
        vcf = config['vcf'],
        db = config['rocksdb']
    params:
        lookup_only = False,
        genome = config['genome']
    output:
        csv = config['result']
    script:
        "./scripts/predict.py"
