configfile: "config.yaml"


rule all:
    input:
        expand(config['rockdb_backup'], genome=['grch37', 'grch38']), 
        config['result']

def precomputed_snv_vcf(wildcards):
    genome = wildcards['genome']
    return config['precomputed'][genome]['snv']


def precomputed_indel_vcf(wildcards):
    genome = wildcards['genome']
    return config['precomputed'][genome]['indel']


rule create_spliceAI_rocksDB:
    input:
        snv = precomputed_snv_vcf,
        indel = precomputed_indel_vcf
    output:
        db = directory(config['rocksdb'])
    script:
        "./scripts/create_rocksdb.py"


rule backup_rocksdb:
    input:
        db = config['rocksdb']
    output:
        backup = directory(config['rockdb_backup']),
        backup_gzip = config['rockdb_backup'] + '.tar.gz'
    script:
        "./scripts/backup_rocksdb.py"


rule predict_spliceAI:
    threads: 1
    resources:
        ntasks = 1,
        mem_mb = 8000,
        gpu = 1,
    input:
        fasta = config['fasta'],
        vcf = config['vcf'],
        db = config['rocksdb']
    params:
        lookup_only = False,
        genome = config['genome']
    output:
        csv = config['result']
    script:
        "./scripts/predict.py"
